steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - gcp-cloudfunction-hello
  - --region=us-east1
  - --source=.
  - --trigger-http
  - --runtime=java17
  - --entry-point=functions.HelloWorld
  - --memory=512MB
  - --allow-unauthenticated